[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
board_build.mcu = esp32c6
board_build.f_cpu = 160000000L
monitor_speed = 115200
board_build.flash_size = 4MB
build_flags =
    -Wno-volatile
    -Wno-missing-field-initializers
    -Wno-unused-variable
    -Wno-implicit-fallthrough
